### ISSUE TITLE
麻烦帮忙看下

### ISSUE THREAD

**Issue by weitemi** [chequer-io/electron-ffi-sample#1]
我安装ffi的时候 总是提示错误[报错截图](https://upload-images.jianshu.io/upload_images/2685430-cdf424d58058ebf8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1000/format/webp)

**Comment by githoniel** [comment]
node-ffi项目不支持node v10，对应版本electron v3，安装v2即可
```
npm i electron@2.0.14
```

**Comment by weitemi** [comment]
> node-ffi项目不支持node v10，对应版本electron v3，安装v2即可
> 
> ```
> npm i electron@2.0.14
> ```

感谢，我把node 10 换成8的最新版安装ffi 就可以了，我看了你的说明 理解的是8以后都行。现在好了，谢谢啊，安装这个ffi模块折腾了好久。
